# version: '3.8'

# services:
#   # PHP Service
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel_app
#     restart: unless-stopped
#     working_dir: /var/www/html
#     volumes:
#       - .:/var/www/html
#     networks:
#       - laravel_network

#   # Nginx Service
#   webserver:
#     image: nginx:alpine
#     container_name: laravel_webserver
#     restart: unless-stopped
#     ports:
#       - "80:80"
#     volumes:
#       - .:/var/www/html
#       - ./docker/nginx:/etc/nginx/conf.d
#     networks:
#       - laravel_network
#     depends_on:
#       - app

#   # MySQL Service
#   db:
#     image: mysql:8.0
#     container_name: laravel_db
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_PASSWORD: secret
#       MYSQL_USER: laravel
#     volumes:
#       - dbdata:/var/lib/mysql
#     networks:
#       - laravel_network

# # Volumes
# volumes:
#   dbdata:
#     driver: local

# # Networks
# networks:
#   laravel_network:
#     driver: bridge
